# Generated by Django 6.0.4 on 2026-04-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('acertos', models.IntegerField()),
                ('tempo_ms', models.IntegerField()),
                ('tempo_texto', models.CharField(max_length=20)),
                ('data_registro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-acertos', 'tempo_ms'],
            },
        ),
    ]
