# Generated by Django 6.0.3 on 2026-04-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='data_registro',
        ),
    ]
