# Generated by Django 6.0.4 on 2026-04-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='nivel',
            field=models.CharField(default='facil', max_length=10),
        ),
    ]
