# Generated by Django 6.0.4 on 2026-04-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_ranking_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
