# Generated by Django 6.0.3 on 2026-04-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_ranking_data_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='data_registro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
